### ISSUE TITLE
how to run inference/test independently

### ISSUE THREAD

**Issue by SeekPoint** [andreamad8/EntNet#7]

**Comment by andreamad8** [comment]
I haven't implemented it yet. Since I was always testing with a given test set. I will make it available soon. 

Else, you can:
`
dic = {entity_net.S:mb_x1,entity_net.Q:mb_x2, entity_net.keep_prob:1.0}
`
`
prediction = tf.run(entity_net.logit, feed_dict=feed_dict)
`
and there you have your prediction
